### ISSUE TITLE
Format SVG code in downloaded file

### ISSUE THREAD

**Issue by maticbasle** [maticbasle/ColorSVG#44]
When you download an icon, the SVG code is not formatted.

<img width="297" alt="screenshot 2018-10-23 at 16 56 19" src="https://user-images.githubusercontent.com/25509076/47369769-b1486780-d6e4-11e8-9b55-d8806d19d0c6.png">

After the first tag, there are 2 spaces and 3 tabs for indenting the second tag. Ideally, it would all be formatted with tab indentation.

**Comment by paescuj** [comment]
Please note that the wrong format is primarily caused by the indentation inconsistency in [index.html](../blob/d36210bb98e7dce19eba8b66d526a315a989ea77/public/index.html). I would rather recommend to fix this in the first line.

Also I personally recommend to use 2 spaces for indentation (especially in web projects, see [1](https://standardjs.com/#standardjs--the-rules) or [2](https://github.com/airbnb/javascript#whitespace--spaces)) and/or add at least a [.editorconfig file](https://editorconfig.org/) to this project.
